import { DataType } from '@/app/types'

export const dataTypesByPropertyName = {
  arcEndingAngle: 'degree',
  arcInnerRadius: 'percent',
  arcStartingAngle: 'degree',
  bottomLeftRadius: 'uint',
  bottomRadii: 'uint',
  bottomRightRadius: 'uint',
  cornerRadius: 'uint',
  fillColor: 'color',
  fillColorBlueChannel: 'uint',
  fillColorGreenChannel: 'uint',
  fillColorHue: 'udegree',
  fillColorLightness: 'percent',
  fillColorRedChannel: 'uint',
  fillColorSaturation: 'percent',
  fillOpacity: 'percent',
  height: 'uint',
  innerRadius: 'percent',
  layerBlur: 'uint',
  leftRadii: 'uint',
  opacity: 'percent',
  pointCount: 'pointCount',
  rightRadii: 'uint',
  rotation: 'degree',
  strokeBottomWeight: 'uint',
  strokeColor: 'color',
  strokeColorBlueChannel: 'uint',
  strokeColorGreenChannel: 'uint',
  strokeColorHue: 'udegree',
  strokeColorLightness: 'percent',
  strokeColorRedChannel: 'uint',
  strokeColorSaturation: 'percent',
  strokeLeftWeight: 'uint',
  strokeOpacity: 'percent',
  strokeRightWeight: 'uint',
  strokeTopWeight: 'uint',
  strokeWeight: 'uint',
  text: 'string',
  topLeftRadius: 'uint',
  topRadii: 'uint',
  topRightRadius: 'uint',
  width: 'uint',
  x: 'int',
  y: 'int',
} satisfies Record<string, DataType>
